name: wecopttool
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pytest
  - matplotlib
  - numpy
  - scipy
  - xarray=0.18.2
  - capytaine=1.2.1
  - autograd=1.3
  - spyder-kernels=1.10
  - pip:
    - mhkit==0.4.0
    - gmsh
    - pygmsh
    - git+https://github.com/LHEEA/meshmagick.git@3.0

