name: _wecopttool
channels:
  - conda-forge
  - defaults
dependencies:
  - argcomplete
  - autograd
  - capytaine=1.2
  - control
  - cyipopt
  - importlib-metadata
  - jinja2
  - lxml
  - meshio
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-repeat
  - pytest-console-scripts
  - requests
  - scikit-learn
  - scipy
  - vtk
  - xarray
  - pip:
    - fatpack
    - gmsh
    - mhkit
    - pecos
    - pygmsh==7.1.8
    - git+https://github.com/LHEEA/meshmagick.git@3.0

