name: wecopttool
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.9
  - pip
  - pytest
  - matplotlib
  - numpy
  - scipy
  - xarray
  - capytaine
  - autograd
  - pip:
    - mhkit
    - gmsh
    - pygmsh
    - git+https://github.com/LHEEA/meshmagick.git@3.0

