{% set name = 'wecopttool' %}
{% set version = '2.0.1a1' %}
package:
  name: 'wecopttool'
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/15/7d/b41cfbc33cee3938eeb8a5a309f5e6295c851123251ed8fb1787cc3a1e31/wecopttool-2.0.1a1.tar.gz
  sha256: 7b6a7e86d1d89cab056670f8c330d6bd13815b76004c40915e27e43d376a294d

build:
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python>=3.8,<3.11
    - pip
    - numpy>=1.20
  run:
    - python>=3.8,<3.11
    - numpy>=1.20
    - scipy
    - capytaine==1.4.0
    - wavespectra
    - meshio
    - matplotlib-base
    - xarray
    - autograd
    - netCDF4
    - jupyter
    - joblib
    
test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - wecopttool

about:
  home: https://snl-waterpower.github.io/WecOptTool/
  license: GNU General Public License v3 (GPLv3)
  license_file: LICENSE
  summary: WEC Design Optimization Toolbox

extra:
  recipe-maintainers:
    - cmichelenstrofer
    - michaelcdevin