package:
  name: "wecopttool"
  version: "2.0"

source:
  url: ../

requirements:
  host:
    - pip
    - python
  run:
    - python>=3.8
    - numpy
    - scipy
    - matplotlib
    - xarray
    - autograd
    - gmsh
    - pygmsh
    - meshio
    - netCDF4
    - capytaine==1.4.0
    - jupyter
    - joblib

about:
  home: https://github.com/SNL-WaterPower/WecOptTool
  license: GNU General Public License v3 (GPLv3)
  license_file: LICENSE
  summary: WEC Design Optimization Toolbox
