package:
  name: "wecopttool"
  version: "2.0.0"

source:
  url: https://files.pythonhosted.org/packages/b0/d0/3b797c4b919a82a561e084cf34fb118e8005efc5c6e843a78a860dcf6557/wecopttool-2.0.0.tar.gz
  sha256: 3cde0669695e951a3dd6b0a2b2afbcb486e4717466b55eac92e842eb36bde419

requirements:
  host:
    - python
    - pip
    - numpy>=1.20
    - wheel
  run:
    - python>=3.8
    - numpy>=1.20
    - scipy
    - matplotlib
    - xarray
    - autograd
    - meshio
    - netCDF4
    - capytaine==1.4.0
    - jupyter
    - joblib
    - wavespectra

about:
  home: https://github.com/SNL-WaterPower/WecOptTool
  license: GNU General Public License v3 (GPLv3)
  license_file: LICENSE
  summary: WEC Design Optimization Toolbox
