{% set pyproject = load_file_data('pyproject.toml') %}
{% set poetry = pyproject.get('tool', {}).get('poetry') %}
{% set name = poetry.get('name') %}
{% set version = poetry.get('version') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3cde0669695e951a3dd6b0a2b2afbcb486e4717466b55eac92e842eb36bde419

build:
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python>=3.8
    - numpy>=1.20
    - scipy
    - matplotlib-base
    - xarray
    - autograd
    - meshio
    - netCDF4
    - capytaine==1.4.0
    - jupyter
    - joblib
    - wavespectra

test:
  imports:
    - wecopttool
  requires:
    - pytest
  commands:
    - pip
    - pytest

about:
  home: {{ poetry.get('urls') }}
  license: {{ poetry.get('license') }}
  license_file: LICENSE
  summary: {{ poetry.get('description') }}

extra:
  recipe-maintainers:
    - cmichelenstrofer
    - michaelcdevin