# Check: package builds, tests pass, documentation builds.
# Report: test coverage
name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.10"]  # PyVer

    steps:
    - uses: actions/checkout@v3

    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: test-env
          use-mamba: true

    - name: Set cache date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Create environment.yml file
      run: |
        echo "name: test-env" >> environment.yml
        echo "" >> environment.yml
        echo "dependencies:" >> environment.yml
        echo "capytaine=1.4.2" >> environment.yml
        echo "wavespectra" >> environment.yml

    - uses: actions/cache@v3
      env:
        CACHE_NUMBER: 0  # increase to reset cache manually
      with:
        path: ${{ matrix.prefix }}
        key: ${{ matrix.label }}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
      id: cache

    - name: Update environment
      run: mamba env update -n my-env -f environment.yml
      if: steps.cache.outputs.cache-hit != 'true'

    # - uses: conda-incubator/setup-miniconda@v2
    #   with:
    #     auto-update-conda: true
    #     python-version: ${{ matrix.python-version }}

    - name: Install libglu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libglu1
      # TODO: Why is this needed? Fix upstream package?

    - name: Install WecOptTool
      shell: bash -l {0}
      run: |
        # conda install -c conda-forge capytaine=1.4.2 wavespectra  # TODO: Hardcoded for Windows. Why needed?
        python3 -m pip install --upgrade pip
        pip3 install coveralls pytest
        pip3 install .

    - name: Run Test
      shell: bash -l {0}
      run: coverage run -m pytest

    - name: Upload coverage data to coveralls.io
      if: ${{ matrix.python-version == 3.10  &&  matrix.os == 'ubuntu-latest' }}  # PyVer
      shell: bash -l {0}
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: build_test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        python3 -m pip install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  documentation:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # PyVer

    - name: Install WecOptTool for documentation
      shell: bash -l {0}
      run: |
        python3 -m pip install --upgrade pip
        pip3 install .[dev]

    - name: Build documentation
      shell: bash -l {0}
      run: |
        cd docs
        make clean
        make linkcheck
        make html
        cd ../
