# Deploy documentation website
name: GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Build and deploy website
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install libglu
      run: sudo apt-get install libglu1
      # TODO: Why is this needed? Fix upstream package?

    - name: Install pandoc
      run: sudo apt-get install pandoc

    - name: Install WecOptTool for documentation
      shell: bash -l {0}
      run: |
        python3 -m pip install --upgrade pip
        pip3 install .[dev]

    - name: Build documentation
      shell: bash -l {0}
      run: |
        cd docs
        make linkcheck
        make html
        cd ../

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
