name: GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and deploy website
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        channels: defaults,conda-forge

    - name: Install WecOptTool for documentation
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        conda install capytaine=1.3
        conda install -c conda-forge pandoc
        pip install git+https://github.com/LHEEA/meshmagick.git@3.3
        pip install .[doc]

    - name: Build documentation
      shell: bash -l {0}
      run: |
        cd docs
        make linkcheck
        make html
        cd ../

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        # publish_branch: gh-pages
        # enable_jekyll: false
        # user_name: 'github-actions[bot]'
        # user_email: 'github-actions[bot]@users.noreply.github.com'
        # commit_message: ${{ github.event.head_commit.message }}
