name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest",]
        python-version: ["3.8", "3.9",]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: defaults,conda-forge

    - name: Install WecOptTool
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install coveralls pytest
        conda install openblas=0.3.18
        conda install capytaine
        if [ "$RUNNER_OS" == "Linux" ]; then
          conda install libglu
        fi
        pip install git+https://github.com/LHEEA/meshmagick.git@3.3
        pip install .[dev]

    - name: Run Test
      shell: bash -l {0}
      run: |
        coverage run -m pytest

    - name: Upload coverage data to coveralls.io
      shell: bash -l {0}
      run: |
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
        COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        python -m pip install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  documentation:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        channels: defaults,conda-forge

    - name: Install WecOptTool for documentation
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        conda install capytaine
        conda install pandoc
        if [ "$RUNNER_OS" == "Linux" ]; then
          conda install libglu
        fi
        pip install git+https://github.com/LHEEA/meshmagick.git@3.3
        pip install .[doc]

    - name: Build documentation
      shell: bash -l {0}
      run: |
        cd docs
        make clean html
        make clean linkcheck
        cd ../
