name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]

    steps:
    - uses: conda-incubator/setup-miniconda@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Install requirements
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        conda create -n wecopttool -c conda-forge capytaine=1.3
        conda activate wecopttool
        pip install coveralls pytest
        pip install -r requirements-ci.txt

    - name: Run Test
      shell: bash -l {0}
      run: |
        conda activate wecopttool
        coverage run -m pytest

    - name: Upload coverage data to coveralls.io
      shell: bash -l {0}
      run: |
        conda activate wecopttool
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
        COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        python -m pip install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
