name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest",]
        python-version: ["3.7", "3.8", "3.9",]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: defaults,conda-forge

    - name: Install WecOptTool
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install coveralls pytest
        conda install capytaine=1.3
        pip install git+https://github.com/LHEEA/meshmagick.git@3.3
        pip install .

    - name: Run Test
      shell: bash -l {0}
      run: |
        coverage run -m pytest

    - name: Upload coverage data to coveralls.io
      shell: bash -l {0}
      run: |
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
        COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        python -m pip install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
