# Check: package builds, tests pass
# TODO: figure out Fortran compilers on Windows so this can be part of tests.yml.
name: Build

on:
  push:
    branches: [ main, v2.0.0-dev ]
  pull_request:
    branches: [ main, v2.0.0-dev ]

jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest",]
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: defaults,conda-forge

    - name: Install WecOptTool
      shell: bash -l {0}
      run: |
        python3 -m pip install --upgrade pip
        pip3 install coveralls pytest
        conda install capytaine
        conda install wavespectra
        pip3 install .

    - name: Run Test
      shell: bash -l {0}
      run: |
        coverage run -m pytest
